---
abstract: 'Use OO to point to a yaml-node'
author:
  - 'Jan Henning Thorsen, C<< <jhthorsen at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-Object
no_index:
  directory:
    - inc
    - t
requires:
  Symbol: 1
  YAML: 0.7
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=YAML-Object
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jhthorsen/yaml-object
version: 0.0401
