--- 
abstract: Use OO to point to a yaml-node
author: 
  - Jan Henning Thorsen, C<< <pm at flodhest.net> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: YAML-Object
no_index: 
  directory: 
    - inc
    - t
requires: 
  YAML: 0
version: 0.03
